### ISSUE TITLE
is there a way to contain multiple directories and select one of those?

### ISSUE THREAD

**Issue by cyberhck** [artspb/phpstorm-library-plugin#1]
Say I want to include IDE stubs of multiple version of a framework, and want to have a settings where user can choose which version of framework s/he is using. Then it should only provide that particular directory which contains IDE stubs for the version of framework.

Is it possible with the current setup? or do I have to do something from ground up?

**Comment by artspb** [comment]
No, unfortunately, it's not possible with this simple API. You need to write a plugin using Java to achieve it.
